Repository hanjoondev/minesweeper, pull requests merged in 2022-09, with the labels that each got.

#26 Close#25 로비채팅 기능
  build.gradle
  src/main/java/com/zerobase/minesweeper/component/MailComponentImpl.java
  src/main/java/com/zerobase/minesweeper/config/WebConfig.java
  src/main/java/com/zerobase/minesweeper/config/WebSocketConfig.java
  src/main/java/com/zerobase/minesweeper/controller/AuthController.java
  src/main/java/com/zerobase/minesweeper/controller/ChattingController.java
  src/main/java/com/zerobase/minesweeper/controller/GameController.java
  src/main/java/com/zerobase/minesweeper/controller/GamerController.java
  src/main/java/com/zerobase/minesweeper/dto/ChatMessage.java
  src/main/java/com/zerobase/minesweeper/dto/ErrorResponse.java
  src/main/java/com/zerobase/minesweeper/dto/GamerStatResponse.java
  src/main/java/com/zerobase/minesweeper/dto/LobbyChatDto.java
  src/main/java/com/zerobase/minesweeper/dto/LobbyChatResponse.java
  src/main/java/com/zerobase/minesweeper/dto/LoginResponse.java
  src/main/java/com/zerobase/minesweeper/dto/Rank.java
  src/main/java/com/zerobase/minesweeper/dto/RankingRequest.java
  src/main/java/com/zerobase/minesweeper/dto/RankingResponse.java
  src/main/java/com/zerobase/minesweeper/dto/TokenDto.java
  src/main/java/com/zerobase/minesweeper/entity/LobbyChat.java
  src/main/java/com/zerobase/minesweeper/entity/Ranking.java
  src/main/java/com/zerobase/minesweeper/exception/GamerException.java
  src/main/java/com/zerobase/minesweeper/exception/GlobalExceptionHandler.java
  src/main/java/com/zerobase/minesweeper/exception/JwtException.java
  src/main/java/com/zerobase/minesweeper/repository/GameRepository.java
  src/main/java/com/zerobase/minesweeper/repository/LobbyChatRepository.java
  src/main/java/com/zerobase/minesweeper/repository/RankingRepository.java
  src/main/java/com/zerobase/minesweeper/security/CorsFilter.java
  src/main/java/com/zerobase/minesweeper/security/JwtAccessDeniedHandler.java
  src/main/java/com/zerobase/minesweeper/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/zerobase/minesweeper/security/SecurityConfig.java
  src/main/java/com/zerobase/minesweeper/security/TokenProvider.java
  src/main/java/com/zerobase/minesweeper/service/AuthService.java
  src/main/java/com/zerobase/minesweeper/service/GameService.java
  src/main/java/com/zerobase/minesweeper/service/GamerService.java
  src/main/java/com/zerobase/minesweeper/service/LobbyChatService.java
  src/main/java/com/zerobase/minesweeper/type/ErrorCode.java
Labels: feature request

#28 Close#25 로비채팅 기능
  build.gradle
  src/main/java/com/zerobase/minesweeper/config/WebConfig.java
  src/main/java/com/zerobase/minesweeper/config/WebSocketConfig.java
  src/main/java/com/zerobase/minesweeper/controller/AuthController.java
  src/main/java/com/zerobase/minesweeper/controller/ChattingController.java
  src/main/java/com/zerobase/minesweeper/dto/ChatMessage.java
  src/main/java/com/zerobase/minesweeper/dto/LobbyChatDto.java
  src/main/java/com/zerobase/minesweeper/dto/LobbyChatResponse.java
  src/main/java/com/zerobase/minesweeper/dto/LoginResponse.java
  src/main/java/com/zerobase/minesweeper/dto/TokenDto.java
  src/main/java/com/zerobase/minesweeper/entity/LobbyChat.java
  src/main/java/com/zerobase/minesweeper/repository/LobbyChatRepository.java
  src/main/java/com/zerobase/minesweeper/security/CorsFilter.java
  src/main/java/com/zerobase/minesweeper/security/SecurityConfig.java
  src/main/java/com/zerobase/minesweeper/security/TokenProvider.java
  src/main/java/com/zerobase/minesweeper/service/AuthService.java
  src/main/java/com/zerobase/minesweeper/service/LobbyChatService.java
  src/main/java/com/zerobase/minesweeper/type/ErrorCode.java
Labels: feature request

#30 fix : Gamer 관련 오류
  src/main/java/com/zerobase/minesweeper/controller/GameController.java
  src/main/java/com/zerobase/minesweeper/controller/GamerController.java
  src/main/java/com/zerobase/minesweeper/dto/GamerDto.java
  src/main/java/com/zerobase/minesweeper/dto/GamerInfoResponse.java
  src/main/java/com/zerobase/minesweeper/dto/GamerLostPasswordRequest.java
  src/main/java/com/zerobase/minesweeper/dto/GamerSignUpRequest.java
  src/main/java/com/zerobase/minesweeper/dto/GamerUpdateNameRequest.java
  src/main/java/com/zerobase/minesweeper/dto/GamerUpdatePasswordRequest.java
  src/main/java/com/zerobase/minesweeper/dto/GamerWithdrawalRequest.java
  src/main/java/com/zerobase/minesweeper/dto/GamersBoardInfoResponse.java
  src/main/java/com/zerobase/minesweeper/entity/Gamer.java
  src/main/java/com/zerobase/minesweeper/exception/GameException.java
  src/main/java/com/zerobase/minesweeper/exception/GlobalExceptionHandler.java
  src/main/java/com/zerobase/minesweeper/repository/GamerRepository.java
  src/main/java/com/zerobase/minesweeper/service/AuthService.java
  src/main/java/com/zerobase/minesweeper/service/GameService.java
  src/main/java/com/zerobase/minesweeper/service/GamerService.java
  src/main/java/com/zerobase/minesweeper/type/ErrorCode.java
Labels: bug

#31 관리자 페이지 버그 수정 및 minor update
  src/main/java/com/zerobase/minesweeper/controller/AdminController.java
  src/main/java/com/zerobase/minesweeper/controller/GameController.java
  src/main/java/com/zerobase/minesweeper/controller/GamerController.java
  src/main/java/com/zerobase/minesweeper/dto/GamerUpdateNameRequest.java
  src/main/java/com/zerobase/minesweeper/dto/GamersBoardInfoResponse.java
  src/main/java/com/zerobase/minesweeper/service/AdminService.java
  src/main/java/com/zerobase/minesweeper/service/GameService.java
  src/main/java/com/zerobase/minesweeper/service/GamerService.java
Labels: bug, enhancement
